# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: true               # on peut utiliser des regex dans allow_origin
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/': null                        # applique ces règles à toutes les URLs
