lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Routes dev Symfony (profiler, assets, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API authentifiée en JWT
        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider

            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            # **Le plus important !**
            custom_authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        # Firewall pour le site web (login, dashboard…)
        main:
            pattern: ^/
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator

            form_login:
                login_path:    app_login
                check_path:    app_login
                username_parameter: email
                password_parameter: password
                enable_csrf:   true
                csrf_parameter:   _csrf_token
                csrf_token_id:    authenticate
            logout:
                path: app_logout
                target: app_login

            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        # L'ordre est important !
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,            roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,          roles: ROLE_ADMIN }
        - { path: ^/astreignable,   roles: ROLE_USER }
        - { path: ^/login$,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$,              roles: IS_AUTHENTICATED_ANONYMOUSLY }
