security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator

            form_login:
                login_path:    app_login
                check_path:    app_login
                username_parameter: email
                password_parameter: password
                enable_csrf:   true
                csrf_parameter:   _csrf_token
                csrf_token_id:    authenticate
                # on supprime default_target_path !
            logout:
                path: app_logout
                target: app_login

            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/admin,        roles: ROLE_ADMIN   }
        - { path: ^/astreignable, roles: ROLE_USER    }
        - { path: ^/login$,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$,            roles: IS_AUTHENTICATED_ANONYMOUSLY }
