services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astreinte-php
    volumes:
      - .:/var/www/html
      - var-tests:/var/www/html/var/tests
    ports:
      - "8010:8001"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: astreinte-db
    restart: always
    environment:
      MYSQL_DATABASE: astreinte
      MYSQL_USER: astreinte
      MYSQL_PASSWORD: astreinte
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8012:3306"
    volumes:
      - astreinte-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: astreinte-pma
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8011:80"
    depends_on:
      - db

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: astreinte-jenkins
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - var-tests:/var/www/html/var/tests
    restart: unless-stopped
    user: root

  sonarqube:
    image: sonarqube:community
    container_name: astreinte-sonarqube
    ports:
      - "9001:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

volumes:
  astreinte-db-data:
  jenkins_home:
  var-tests:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
