services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astreinte-php
    volumes:
      - .:/var/www/html
    ports:
      - "8010:8001"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: astreinte-db
    restart: always
    environment:
      MYSQL_DATABASE: astreinte
      MYSQL_USER: astreinte
      MYSQL_PASSWORD: astreinte
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8012:3306"
    volumes:
      - astreinte-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: astreinte-pma
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8011:80"
    depends_on:
      - db

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: astreinte-jenkins
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    user: root

volumes:
  astreinte-db-data:
  jenkins_home:
