controllers:
    resource: '../src/Controller/'
    type: annotation

app_home:
    path: /
    controller: App\Controller\SecurityController::home

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

astreignable_dashboard:
    path: /astreignable
    controller: App\Controller\Astreignable\DashboardController::index

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/'
    type: annotation
    prefix: /admin

easy_admin_astreignable:
    resource: '@EasyAdminBundle/Controller/'
    type: annotation
    prefix: /astreignable
